---
# Revised 9/5/19 to postgresql
#

# - block:
#   - name: Create databases for sites
#     postgresql_db:
#       name: "{{ site_env.db_name }}"
#       state: present
#       login_host: "{{ site_env.db_host }}"
#       login_user: "{{ postgresql_db_admin }}"
#       login_password: "{{ postgresql_db_admin_password }}"
#     with_dict: "{{ wordpress_sites }}"

#   - name: Create/assign database user to db and grant permissions
#     postgresql_user:
#       name: "{{ site_env.db_user }}"
#       password: "{{ site_env.db_password }}"
#       # host: "{{ site_env.db_user_host }}"
#       priv: "ALL"
#       db: "{{ site_env.db_name }}"
#       state: present
#       login_host: "{{ site_env.db_host }}"
#       login_user: "{{ postgresql_user }}"
#       login_password: "{{ postgresql_postgres_password }}"
#     with_dict: "{{ wordpress_sites }}"

#   when: site_uses_local_db and item.value.db_create | default(true)
