---
- name: Upgrade-dist all packages
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 3600

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: Reboot host
  reboot:
    msg: "Reboot initiated by Ansible"
